#!/usr/bin/env bash
# A BAsh script that displays "To infinity and beyond" indefinitely but
# displays "I am invincible!!!" when receiving a SIGTERM signal

msg()
{
	echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2

done
