#!/usr/bin/env bash
# This file displays numbers from 1 to 100
# Displays 'FizzBuzz' when a number is a multiple of 3 and 5
# Displays 'Fizz' when a number is a multiple of 3
# Displays 'Buzz' when a number is a multiple  of 5
# Otherwise, it displays the number
# In a List format

x=1

while [ $x -le 100 ]
do
	if (( x % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( x % 5 == 0 ))
	then
		echo "Buzz"
	elif (( x % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$x"
	fi
	x=$(( x + 1 ))
done
