#!/usr/bin/env bash
# This file displays 'Best School' 10 times

x=1
while [ $x -le 10 ]
do
	echo "Best School"
	x=$(( x + 1))
done


#x=1; while [ $x -le 10] do echo "Best School" x=$(( $x + 1)); done
