#!/usr/bin/env bash
# This file displays the content of the current directory
# in a list format, where only the part if the name
# after the dash is displayed

ls_files="$(ls)"

for file in $ls_files;
do
	echo "$file" | cut -d "-" -f2
done
