#!/usr/bin/env bash
# This file gives information about the 'school' file
# It uses 'if else' condition to check the existence of the file
# And prints the corresponding text for each case accordingly

sch_file="school"

if [ -e "sch_file" ]
then
	echo "$sch_file file exists"

	if [ -s "$sch_file" ]
	then
		echo "$sch_file file is not empty"
	else
		echo "$sch_file file is empty"
	fi

	if [ -f "$sch_file" ]
	then
		echo "$sch_file is a regular file"
	fi

else
	echo "$sch_file file does not exist"
fi
